import React from 'react';
import { PublicNavbar } from '../../components/public/PublicNavbar';
import { PublicFooter } from '../../components/public/PublicFooter';
import { FileText, Shield, CheckCircle } from 'lucide-react';

export function TermsPage() {
  return (
    <div className="min-h-screen bg-brand-canvas flex flex-col">
      <PublicNavbar />

      {/* Hero */}
      <section className="bg-brand-navy text-white pt-32 pb-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <span className="bg-brand-green/20 text-brand-green-light text-xs font-black uppercase px-3 py-1 rounded-full inline-block mb-3">
            LEGAL AGREEMENTS
          </span>
          <h1 className="text-4xl md:text-5xl font-display font-extrabold mb-4">Terms of Service</h1>
          <p className="text-gray-400 text-sm md:text-base">Last updated: August 26, 2026</p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 flex-1">
        <div className="max-w-4xl mx-auto px-4 bg-white border border-brand-line rounded-2xl p-8 md:p-12 shadow-card space-y-8 text-xs sm:text-sm text-slate-700 leading-relaxed">
          <div className="space-y-3">
            <h2 className="text-lg font-display font-bold text-brand-ink">1. Acceptance of Terms</h2>
            <p>
              By accessing or using <strong>MarketPilot AI</strong> ("Platform", "Service"), you agree to be bound by these Terms of Service. If you are entering into this agreement on behalf of a company or legal entity, you represent that you have the authority to bind such entity to these terms.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-display font-bold text-brand-ink">2. Ownership of AI Generated Content</h2>
            <p>
              <strong>You own all content, strategy pillars, scripts, ad copy, and campaign briefs generated by MarketPilot AI for your workspace.</strong> MarketPilot AI claims no intellectual property rights over the marketing material produced using your account.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-display font-bold text-brand-ink">3. Acceptable Use Policy</h2>
            <p>
              You agree not to use the Platform to generate deceptive marketing, spam campaigns, prohibited medical cures, illegal products, or content that violates third-party copyright, Meta Advertising Standards, or TikTok Community Guidelines.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-display font-bold text-brand-ink">4. Subscriptions, Upgrades & Cancellations</h2>
            <p>
              Pro and Enterprise plans are billed in advance on a recurring monthly or annual basis. You may cancel your subscription at any time via your account dashboard. Upon cancellation, your workspace retains active access until the conclusion of the paid billing cycle.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-display font-bold text-brand-ink">5. 14-Day Money-Back Guarantee</h2>
            <p>
              We stand behind the quality of our AI strategist. If you are not satisfied with MarketPilot AI Pro within the first 14 days of your initial purchase, contact our support team at <a href="mailto:support@marketpilot.ai" className="text-brand-green font-bold underline">support@marketpilot.ai</a> for a full, no-questions-asked refund.
            </p>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
